- name: install packages
  hosts: frontend
  become: yes # become sudo user
  tasks:
  - name: install packages
    ansible.builtin.packages:
    msg: "{{ item }}"
    state: installed
  loop:
  - mysql
  - nginx
  - zip