- name: user creation
  hosts: local
  connection: local
  tasks:
  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true  #  it only prevents the playbook from stopping. The task will still be marked as FAILED, but the play will continue.

  - name: create user
    become: yes
    ansible.builtin.command: useradd roboshop
    when: output.rc != 0 # it means above task is failure

  - name: user already exist
    ansible.builtin.debug:
      msg: user already exist
    when: output.rc == 0